name: comuni-italiani

on:
#   schedule:
#    - cron: '0 1 1 * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo content
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Build docker images
        run: docker build -t erighetto/comuni-italiani-php:latest .

      - name: Update data
        run: docker run --rm -t -v "${PWD}:/app" erighetto/comuni-italiani-php php ./bin/minicli update

      - name: Update update_at.txt
        run: |
          date '+%F %H:%M %Z' >| update_at.txt

      - name: Commit files
        run: |
          git config --local user.email "erighetto[bot]@users.noreply.github.com"
          git config --local user.name "Comuni Italiani PHP Bot"
          git add -A
          git commit -m "Update Data (`date '+%F %H:%M %Z'`)" -a
          git branch -u origin/main
          git push